---
# tasks file for adipriyantobpn.repo-epel
- block:

  - name: include yum repository variable file
    include_vars: "repo-{{ repo_location }}.yml"

  - name: install EPEL yum repository
    yum:
      name: "{{ epel_repoinstaller_url }}"
      state: present
    register: epel_install_result
    until: '"failed" not in epel_install_result'
    retries: 5
    delay: 10

  - name: import EPEL GPG key
    rpm_key:
      key: "{{ epel_gpgkey_url.replace('file://', '') }}"
      state: present
    ignore_errors: "{{ ansible_check_mode }}"

  - name: configure EPEL yum repository
    yum_repository:
      name: "{{ item.name.lower() }}"
      description: "Extra Packages for Enterprise Linux $releasever - $basearch"
      baseurl: "{{ item.baseurl }}"
      gpgkey: "{{ epel_gpgkey_url }}"
      gpgcheck: yes
      enabled: "{{ item.enabled }}"
      file: "{{ item.file }}"
      state: present
    with_items:
      - { name: EPEL        ,file: "epel"      ,enabled: "{{ epel_enabled }}"         ,baseurl: "{{ epel_baseurl }}" }
  become: True